name              'beyondcompare'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides beyondcompare_package and beyondcompare_git_config resources for Beyond Compare on Windows'
source_url        'https://github.com/sous-chefs/beyondcompare'
issues_url        'https://github.com/sous-chefs/beyondcompare/issues'
chef_version      '>= 15.3'
version           '2.1.0'

supports 'windows'
