name             'beyondcompare'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/beyondcompare'
issues_url       'https://github.com/windowschefcookbooks/beyondcompare/issues'
license          'Apache 2.0'
description      'Installs/Configures Beyond Compare'
version          '1.0.0'
supports         'windows'
