name             'beyondcompare'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/beyondcompare'
issues_url       'https://github.com/windowschefcookbooks/beyondcompare/issues'
chef_version     '>= 13.0'
license          'Apache-2.0'
description      'Installs/Configures Beyond Compare'
version          '2.0.8'
supports         'windows'
depends          'windows'
